# Generated by Django 4.1.3 on 2022-12-09 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(null=True, upload_to="profileImage/"),
                ),
                (
                    "idea_type",
                    models.CharField(
                        choices=[
                            ("Business Idea", "Business Idea"),
                            ("Tech Idea", "Tech Idea"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[("Selling", "Selling"), ("Investing", "Investing")],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("DOB", models.DateTimeField(max_length=10, null=True)),
                ("address", models.CharField(max_length=80, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Others", "Others"),
                            ("Not prefer to say", "Not prefer to say"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("phone_number", models.CharField(max_length=14, null=True)),
                ("staff", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
