# Generated by Django 4.1.3 on 2022-12-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=25, null=True)),
                ("last_name", models.CharField(blank=True, max_length=25, null=True)),
                ("email", models.EmailField(blank=True, max_length=50, null=True)),
                ("messages", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="uploadIdea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fileToUpload", models.FileField(null=True, upload_to="ideas/")),
                (
                    "purpose",
                    models.CharField(
                        choices=[("Selling", "Selling"), ("Investing", "Investing")],
                        max_length=20,
                    ),
                ),
                (
                    "worth",
                    models.CharField(
                        choices=[
                            ("$0-$100", "$0-$100"),
                            ("$100-$1000", "$100-$1000"),
                            ("$1000-$10000", "$1000-$10000"),
                            ("$10000 above", "$1000 above"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pincode", models.CharField(max_length=6)),
                ("email", models.EmailField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
