# Generated by Django 4.1.3 on 2022-12-12 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("serviceapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadidea",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="uploadidea",
            name="fileToUpload",
            field=models.FileField(null=True, upload_to="ideas/% Y/% m/ % d/"),
        ),
    ]
