# Generated by Django 4.1.3 on 2022-12-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serviceapp", "0002_uploadidea_user_alter_uploadidea_filetoupload"),
    ]

    operations = [
        migrations.RemoveField(model_name="uploadidea", name="user",),
        migrations.AddField(
            model_name="uploadidea",
            name="user_id",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
