# Generated by Django 4.1.3 on 2022-12-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serviceapp", "0003_remove_uploadidea_user_uploadidea_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadidea",
            name="status",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
