# Generated by Django 4.1.3 on 2022-12-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serviceapp", "0004_uploadidea_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadidea",
            name="status",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
