# Generated by Django 4.1.3 on 2022-12-13 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("serviceapp", "0005_alter_uploadidea_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadidea",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
