# Generated by Django 4.1.3 on 2022-12-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serviceapp", "0006_uploadidea_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadidea",
            name="description",
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
