# Generated by Django 4.1.3 on 2022-12-14 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "serviceapp",
            "0008_uploadidea_payment_alter_uploadidea_filetoupload_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="uploadidea", name="payment",),
    ]
