# Generated by Django 4.1.3 on 2022-12-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serviceapp", "0009_remove_uploadidea_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadidea",
            name="payment",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
