# Generated by Django 4.1.3 on 2022-12-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serviceapp", "0010_uploadidea_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="bugsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bug_type",
                    models.CharField(
                        choices=[
                            ("Social Media Bug", "Social Media Bug"),
                            ("Nigeria BankApp Bugs", "Nigeria BankApp Bugs"),
                            ("Apple Device Bugs", "Apple Device Bugs"),
                            ("Android Device Bugs", "Android Device Bugs"),
                            ("others", "others"),
                        ],
                        max_length=30,
                    ),
                ),
                ("bug_name", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=225)),
            ],
        ),
        migrations.AlterField(
            model_name="uploadidea",
            name="payment",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
