# Generated by Django 4.1.7 on 2023-03-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0011_bugsmodel_alter_uploadidea_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugsmodel',
            name='bug_name',
            field=models.CharField(choices=[('Facebook Bugs', 'Facebook Bugs'), ('Instagram Bugs', 'Instagram Bugs'), ('Twitter Bugs', 'Twitter Bugs'), ('Snapchat Bugs', 'Snapchat Bugs'), ('Tiktok Bugs', 'Tiktok Bugs'), ('Whatsapp Bugs', 'Whatsapp Bugs'), ('', ''), ('Zenith Bank', 'Zenith Bank'), ('UBA Bank', 'UBA Bank'), ('GT Bank', 'GT Bank'), ('Access Bank', 'Access Bank'), ('Wema Bank', 'Wema Bank'), ('', ''), ('Iphone', 'Iphone'), ('MACBOOK', 'MACBOOK'), ('Apple Watch', 'Apple Watch'), ('', ''), ('Android phone', 'Android phone'), ('others(please specify)', 'others(please specify)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='bugsmodel',
            name='bug_type',
            field=models.CharField(choices=[('Social Media Bug', 'Social Media Bug'), ('Nigeria BankApp Bugs', 'Nigeria BankApp Bugs'), ('Apple Device Bugs', 'Apple Device Bugs'), ('Android Device Bugs', 'Android Device Bugs'), ('Tech bugs', 'Tech bugs'), ('General bugs', 'General bugs')], max_length=30),
        ),
    ]
